from enum import Enum


class ClaimCategory(str, Enum):
    CONSULTATION = "CONSULTATION"
    DIAGNOSTIC = "DIAGNOSTIC"
    PHARMACY = "PHARMACY"
    DENTAL = "DENTAL"
    VISION = "VISION"
    ALTERNATIVE_MEDICINE = "ALTERNATIVE_MEDICINE"


class DocumentType(str, Enum):
    PRESCRIPTION = "PRESCRIPTION"
    HOSPITAL_BILL = "HOSPITAL_BILL"
    LAB_REPORT = "LAB_REPORT"
    PHARMACY_BILL = "PHARMACY_BILL"
    DIAGNOSTIC_REPORT = "DIAGNOSTIC_REPORT"
    DENTAL_REPORT = "DENTAL_REPORT"
    DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY"
    UNKNOWN = "UNKNOWN"


class DocumentQuality(str, Enum):
    GOOD = "GOOD"
    DEGRADED = "DEGRADED"
    UNREADABLE = "UNREADABLE"


class Decision(str, Enum):
    APPROVED = "APPROVED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    HALTED = "HALTED"


class RejectionCode(str, Enum):
    WAITING_PERIOD = "WAITING_PERIOD"
    PER_CLAIM_EXCEEDED = "PER_CLAIM_EXCEEDED"
    SUM_INSURED_EXCEEDED = "SUM_INSURED_EXCEEDED"
    OPD_LIMIT_EXCEEDED = "OPD_LIMIT_EXCEEDED"
    SUB_LIMIT_EXCEEDED = "SUB_LIMIT_EXCEEDED"
    EXCLUDED_CONDITION = "EXCLUDED_CONDITION"
    EXCLUDED_LINE_ITEM = "EXCLUDED_LINE_ITEM"
    PRE_AUTH_MISSING = "PRE_AUTH_MISSING"
    NON_COVERED_RELATIONSHIP = "NON_COVERED_RELATIONSHIP"
    INACTIVE_POLICY = "INACTIVE_POLICY"
    DEADLINE_EXCEEDED = "DEADLINE_EXCEEDED"
    BELOW_MIN_AMOUNT = "BELOW_MIN_AMOUNT"


class HaltCode(str, Enum):
    DOCUMENT_TYPE_MISMATCH = "DOCUMENT_TYPE_MISMATCH"
    DOCUMENT_UNREADABLE = "DOCUMENT_UNREADABLE"
    PATIENT_NAME_MISMATCH = "PATIENT_NAME_MISMATCH"
    UNKNOWN_MEMBER = "UNKNOWN_MEMBER"
    UNKNOWN_CATEGORY = "UNKNOWN_CATEGORY"


class FraudSignal(str, Enum):
    SAME_DAY_LIMIT = "SAME_DAY_LIMIT"
    MONTHLY_LIMIT = "MONTHLY_LIMIT"
    HIGH_VALUE = "HIGH_VALUE"
    SCORE_THRESHOLD = "SCORE_THRESHOLD"


class StageStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"
    DEGRADED = "DEGRADED"
